import re
from playwright.sync_api import Playwright, sync_playwright, expect
import pytest
from playwright.sync_api import Page, expect, sync_playwright


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://staging.connectable.site/login")
    page.get_by_role("textbox", name="E-mail").click()
    page.get_by_role("textbox", name="E-mail").fill("w.project.portal3@gmail.com")
    page.get_by_test_id("login-password").click()
    page.get_by_test_id("login-password").fill("111")
    page.get_by_text("Log in").click()
    page.get_by_role("textbox", name="Find").click()
    page.get_by_role("textbox", name="Find").fill("testconn")
    page.get_by_role("table").locator("div").filter(has_text="testconn27 testconn27").first.click()
    page.get_by_role("row", name="testconn27 testconn27").locator("a").click()
    page.get_by_text("Клонировать").click()
    page.get_by_role("dialog", name="Clone client").get_by_role("textbox").first.click()
    page.get_by_role("dialog", name="Clone client").get_by_role("textbox").first.fill("atc27")
    page.get_by_role("dialog", name="Clone client").get_by_role("textbox").nth(1).click()
    page.get_by_role("dialog", name="Clone client").get_by_role("textbox").nth(1).fill("atc27")
    page.get_by_label("Clone client").get_by_text("Save").click()
    page.get_by_text("OK").first.click()
    page.get_by_label("icon: check-circle").locator("svg").click()
    page.get_by_text("users: 91").click()
    page.get_by_text("tags:").click()
    page.get_by_text("groups:").click()
    page.get_by_text("moods:").click()
    page.get_by_text("vacations:").click()
    page.get_by_text("link_blocks:").click()
    page.get_by_text("mailings:").click()
    page.get_by_text("structs:").click()
    page.get_by_text("dept_users:").click()
    page.get_by_text("shop_items:").click()
    page.get_by_text("shops:").click()
    page.get_by_text("achieves:").click()
    page.get_by_text("templates:").click()
    page.get_by_text("events:").click()
    page.get_by_text("polls:").click()
    page.get_by_text("articles:").click()
    page.get_by_text("vacantions:").click()
    page.get_by_text("sgs:").click()
    page.get_by_text("bps:").click()
    page.get_by_text("step_tasks:").click()
    page.get_by_text("adapt_steps:").click()
    page.get_by_text("adapt_tracks:").click()
    page.get_by_text("adapts:").click()
    page.get_by_text("rooms:").click()
    page.get_by_text("chats:").click()
    page.get_by_text("task_comments:").click()
    page.get_by_text("tasks: 23").click()
    page.get_by_text("desks:").click()
    page.get_by_text("post_comments:").click()
    page.get_by_text("posts:").click()
    page.get_by_role("button", name="OK").click()
    page.get_by_role("button", name="Close").click()
    page.get_by_text("Админ Админович").click()
    page.get_by_text("Logout").click()
    page.get_by_role("textbox", name="Workspace").click()
    page.get_by_role("textbox", name="Workspace").fill("atc27")
    page.get_by_role("textbox", name="E-mail").click()
    page.get_by_role("textbox", name="E-mail").fill("t2@gmail.com")
    page.get_by_test_id("login-password").click()
    page.get_by_test_id("login-password").fill("111111")
    page.get_by_text("Log in").click()
    page.get_by_text("Стена").click()
    page.locator(".post-wrapper").first.click()
    page.get_by_role("img", name="img").click()
    page.locator("#page div").filter(has_text="img 1 /").nth(1).click()
    page.get_by_role("button", name="Close (Esc)").click()
    page.get_by_text("Мы в СМИ О нашей платформе написали в издании об интранете, корпоративном ТВ и д").click()
    page.get_by_text("Привет, команда!Как вы знаете, мы стараемся максимально автоматизировать все, до").click()
    page.get_by_text("Друзья, привет! Лето в самом разгаре и мы поняли, что сейчас самое время напомни").click()
    page.get_by_text("Лента событий").click()
    page.get_by_text("@Наталья Русакова, С днем рождения!").click()
    page.get_by_text("@Наталья Русакова Спасибо большое за оказанную помощь в проекте!)").click()
    page.get_by_text("@Ксения Петрова , как дела?").click()
    page.get_by_text("@Никита Добрынин за помощь с коммуникацией и организацией").click()
    page.get_by_text("Структура").click()
    page.get_by_role("img").filter(has_text="Главное управление Сергей Наумов Управляющий партнер Наталья Русакова Руководите").click()
    page.get_by_text("Адресная книга").click()
    page.get_by_role("table").locator("div").filter(has_text="Попова Галина g.malkova@").first.click()
    page.get_by_text("Дни рождения").click()
    page.get_by_text("Дни рождения июнь 27").click()
    page.get_by_role("main").locator("svg").click()
    page.get_by_text("График отпусков").click()
    page.get_by_text("Группы").click()
    page.get_by_text("Внутри HR").click()
    page.locator("div").filter(has_text="Группы").nth(3).click()
    page.get_by_text("Группы").click()
    page.get_by_text("Клуб путешественников 45 участников Открытая группа 39+").click()
    page.get_by_text("Клуб путешественников").click()
    page.get_by_text("Тест").click()
    page.get_by_text("База знаний").click()
    page.get_by_text("идей онлайн-тимбилдинга для компаний на удалёнке").click()
    page.locator("div:nth-child(3) > .body > span > div > div:nth-child(2) > .back-img").first.click()
    page.get_by_text("Лето — традиционная пора тимбилдингов и выездных корпоративов. Но только не лето").click()
    page.get_by_text("Многие компании оставили сотрудников работать из дома и после окончания самоизол").click()
    page.get_by_role("paragraph").filter(has_text="Мы собрали в этом обзоре 12").click()
    page.get_by_text("Заявки").click()
    page.get_by_text("📝Справки").click()
    page.get_by_text("🖇️АХО").click()
    page.get_by_text("🧮 Внутренние службы").click()
    page.get_by_text("📃 Отдел кадров").click()
    page.get_by_text("👨‍🎨 Маркетинг и дизайн").click()
    page.get_by_text("🤗 Забота о сотрудниках").click()
    page.get_by_role("link", name="Справка о периоде работы").click()
    page.get_by_text("Добрый день!В этом разделе вы можете заказать справку, подтверждающую период раб").click()
    page.get_by_role("tab", name="Шаги").click()
    page.get_by_text("Для действующих сотрудников").click()
    page.get_by_text("Предложить идею").click()
    page.get_by_text("Геймификация").click()
    page.get_by_text("Термос").click()
    page.get_by_text("Кружка").click()
    page.get_by_text("Наклейка").click()
    page.get_by_text("Чехол").click()
    page.get_by_text("Кепка").click()
    page.get_by_text("12").first.click()
    page.locator("div:nth-child(4) > div > .col > .flex-between > .f-align-center > .svg-icon > circle").click()
    page.get_by_text("Доска задач").click()
    page.get_by_text("Маркетинг Марина Бильдякова").click()
    page.get_by_text("Оценка задач 1 Продуктовый вебинар 5 Добавить карточку").click()
    page.get_by_text("В работе 4 Переписать шаблоны уведомлений 9 Продуктовый вебинар 3").click()
    page.get_by_text("Новые задачи 1 Поиск поставщика по \"Брендированию\" 1 0/4 Добавить карточку").click()
    page.get_by_text("Адаптация").click()
    page.get_by_text("Тут весь путь адаптация для сотрудников которые работают в департаментах продаж,").click()
    page.get_by_text("Администрирование").click()
    page.get_by_role("tab", name="Все сотрудники (91)").click()
    page.get_by_text("Админ Админовский").click()
    page.get_by_text("Выйти").click()
    page.get_by_role("textbox", name="Код компании").click()
    page.get_by_role("textbox", name="Код компании").fill("")
    page.get_by_role("textbox", name="E-mail").click()
    page.get_by_role("textbox", name="E-mail").fill("w.project.portal3@gmail.com")
    page.get_by_test_id("login-password").click()
    page.get_by_test_id("login-password").fill("111")
    page.get_by_text("Войти в систему").click()
    page.get_by_role("textbox", name="Find").click()
    page.get_by_role("textbox", name="Find").fill("at")
    page.get_by_role("table").locator("div").filter(has_text="atc27 atc27").first.click()
    page.get_by_role("row", name="atc27 atc27").locator("a").click()
    page.get_by_text("Удалить").click()
    page.get_by_role("checkbox", name="I confirm to wipe all data of").check()
    page.get_by_label("Full remove client").get_by_text("Save").click()
    page.get_by_text("ОК").click()
    page.get_by_role("button", name="OK").click()
    page.get_by_text("Админ Админович").click()
    page.get_by_text("Logout").click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
